name: S3

on:
  push:
    paths:
      - 'S3/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: S3
          auto_approve: true
        env:
          TF_ACTION_WORKING_DIR: 'S3'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
